export const ROLES = [
  "super_admin",
  "business_owner",
  "branch_manager",
  "hr_manager",
  "inventory_manager",
  "procurement_manager",
  "employee",
] as const;

export type UserRole = (typeof ROLES)[number];

export const RESOURCES = [
  "dashboard",
  "company",
  "branch",
  "employee",
  "attendance",
  "leave",
  "recruitment",
  "performance",
  "product",
  "supplier",
  "purchase",
  "inventory",
  "stock_transfer",
  "customer",
  "notification",
  "report",
  "audit",
  "user",
] as const;

export type Resource = (typeof RESOURCES)[number];

export const ACTIONS = [
  "view",
  "create",
  "edit",
  "delete",
  "approve",
  "export",
  "assign",
  "archive",
] as const;

export type Action = (typeof ACTIONS)[number];

export const DEFAULT_TIMEZONE = "Asia/Muscat";
export const DEFAULT_GPS_RADIUS_M = 100;
export const DEFAULT_PAGE = 1;
export const DEFAULT_LIMIT = 20;
export const MAX_LIMIT = 100;

export const ROLE_PERMISSIONS: Record<UserRole, string[]> = {
  super_admin: ["*"],
  business_owner: [
    "dashboard:view",
    "company:view",
    "company:edit",
    "branch:*",
    "employee:*",
    "attendance:*",
    "leave:*",
    "recruitment:*",
    "performance:*",
    "product:*",
    "supplier:*",
    "purchase:*",
    "inventory:*",
    "stock_transfer:*",
    "customer:*",
    "notification:*",
    "report:*",
    "user:*",
  ],
  branch_manager: [
    "dashboard:view",
    "branch:view",
    "employee:view",
    "employee:edit",
    "attendance:*",
    "leave:view",
    "leave:approve",
    "recruitment:view",
    "recruitment:edit",
    "performance:view",
    "performance:edit",
    "product:view",
    "supplier:view",
    "purchase:view",
    "purchase:create",
    "purchase:approve",
    "inventory:view",
    "inventory:edit",
    "stock_transfer:view",
    "stock_transfer:create",
    "stock_transfer:approve",
    "customer:view",
    "customer:create",
    "notification:view",
    "report:view",
    "report:export",
  ],
  hr_manager: [
    "dashboard:view",
    "company:view",
    "branch:view",
    "employee:*",
    "attendance:view",
    "attendance:create",
    "attendance:edit",
    "attendance:delete",
    "attendance:approve",
    "leave:*",
    "recruitment:*",
    "performance:*",
    "notification:*",
    "report:*",
  ],
  inventory_manager: [
    "dashboard:view",
    "branch:view",
    "product:*",
    "supplier:view",
    "purchase:view",
    "purchase:create",
    "purchase:approve",
    "inventory:*",
    "stock_transfer:*",
    "customer:*",
    "notification:view",
    "report:view",
    "report:export",
  ],
  procurement_manager: [
    "dashboard:view",
    "branch:view",
    "product:view",
    "supplier:*",
    "purchase:*",
    "inventory:view",
    "stock_transfer:view",
    "customer:view",
    "customer:create",
    "notification:view",
    "report:view",
    "report:export",
  ],
  employee: [
    "dashboard:view",
    "employee:view",
    "attendance:view",
    "attendance:create",
    "leave:view",
    "leave:create",
    "performance:view",
    "notification:view",
  ],
};
